POST http://localhost:8888/image/blur
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="test.jpg"
Content-Type: image/jpg

< ./assets/test.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--